import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
  },
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="fr">
      <body className="font-manrope text-base font-medium leading-normal">
        <h1 className="sr-only">Developpement </h1>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
